## Configuration for Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true # For local development. Set to false if you want to use the hostname in a DNS-enabled environment
    hostname: ${HOSTNAME:localhost}

## Configuration for App name and Spring Data
spring:
  application:
    name: microservice_login
  datasource:
    url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres
    username: postgres.fmwzbosrxtoewrmnnnyw
    password: bn09QETmHBdpjxmn
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


## Instance port
server:
  port: 8080

